version: '3'
services:
  webserver:
    build:
      context: './bin/${PHPVERSION}'
#    image: php:7.4.14-apache
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    restart: always
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
      - '${HOST_MACHINE_SECURE_HOST_PORT}:443'
    links:
      - database
    volumes:
      - '${DOCUMENT_ROOT-./app}:/var/www/html'
      - '${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini'
      - '${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled'
      - '${LOG_DIR-./logs/apache2}:/var/log/apache2'
    environment:
      PMA_PORT: '${HOST_MACHINE_PMA_PORT}'

  database:
    image: mysql:8
    container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '${HOST_MACHINE_MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database
    environment:
      ADMINER_PLUGINS: 'table-structure tables-filter dump-zip dump-json'
      ADMINER_DESIGN: 'mvt'